app:
  name: ens-front
  # springdoc url 정보
  desc: 전자고지 Front API
  url: 'http://localhost:${server.port}${server.servlet.context-path:}'
  # parameter 로그 출력 형식 - CUSTOM : LoggerAspect 사용,  PAYLOAD : CommonsRequestLoggingFilter 사용
  param.log.type: PAYLOAD
  # param.log.type = CUSTOM인 경우 api 호출 결과 출력 여부
  result.log.trace: true
  # SQL 로그 : p6spy
  sql.logging.enabled: true
  jpa:
    enabled: false

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
    session.timeout: 3600 #sec
    encoding:
      enabled: true
      charset: utf-8
      force: true

spring:
  profiles:
    active: '@springProfilesActive@'
    include:
      - app

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: true  # 새로고침시 즉시 반영 하려면 false - 개발시
    template-resolver-order: 0

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    enabled: false
    path: /api-docs
  swagger-ui:
    enabled: false # default true
    path: /swagger-ui.html
    csrf:
      enabled: false
  version: 'v1'   # API 문서 버전
  default-consumes-media-type: application/json # default consume media type
  default-produces-media-type: application/json # default produce media type
  model-and-view-allowed: true                  # ModelAndView 허용 - excel download시 필요

#-----------------------------------------------------------------
#  logback-spring.xml 로 설정시 스프링의 환경변수를 로그백 시스템 환경변수로 사용
#  logging.file.name / path => LOG_FILE,  LOG_PATH
#  logging.charset.console / file => CONSOLE_LOG_CHARSET, FILE_LOG_CHARSET
#  logging.pattern.console / file => CONSOLE_LOG_PATTERN, FILE_LOG_PATTERN
#-----------------------------------------------------------------
logging:
  charset:
    console: UTF-8
    file: UTF-8
  exception-conversion-word: '%wEx'
  level:
    root: error
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%18.18thread]){magenta} %clr([%-35.35logger{35}::%-25.25method{25}:%4line]){cyan} %clr(%m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}){faint}'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} [%18.18thread] [%-35.35logger{35}::%-25.25method{25}:%4line] %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
  file:
    path: /Users/minuk/data/ens/logs
    name: ${app.name}

