#-----------------------------------------------------------------------
#   local 설정
#-----------------------------------------------------------------------
spring:
  devtools:
    livereload:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: debug
  file:
    # 로그파일 위치 : FIXME :: 로그파일 위치 지정
    path: D:/data/ens/logs
#    path: /Users/minuk/data/ens/logs

# ==================================================================================================================
# JPA logging lib setting
# ==================================================================================================================
decorator:
  datasource:
    p6spy:
      enable-logging: ${app.sql.logging.enabled}
