#-----------------------------------------------------------------------
#   JPA 설정
#-----------------------------------------------------------------------

app:
  # jpa 활성 여부
  jpa:
    enabled: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # 템플릿 view 화면의 렌더링이 끝날 때 까지 Lazy fetch 가 가능하도록 해주는 속성
    open-in-view: false
    generate-ddl: false
    show-sql: true
    properties:
      order_inserts: true
      order_updates: true
      default_batch_fetch_size: ${chunkSize:100}
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      physical_naming_strategy: kr.xit.core.spring.config.support.LowercaseSnakePhysicalNamingStrategy
      hibernate:
        hbm2ddl:
          auto: none
        import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        format_sql: true
        use_sql_comments: false
      jdbc:
        batch_size: 20
        lob:
          # postgres 사용시 createLob() 미구현 경고 삭제
          non_contextual_creation: true
      # Jdbc 환경구성을 하는 과정에서 Default Metadata를 사용할 지 여부
      temp:
        use_jdbc_metadata_defaults: false

# ==================================================================================================================
# JPA logging lib setting
# ==================================================================================================================
decorator:
  datasource:
    p6spy:
      # profiles 별로 정의
      #enable-logging: true
      multiline: true
      logging: slf4j
      custom-appender-class: com.p6spy.engine.spy.appender.Slf4JLogger
      log-format: com.xit.core.config.support.P6spySqlFormatConfiguration
      tracing:
        include-parameter-values: true
