app:
  url: 'localhost:${server.port}'
  result.log.trace: true

spring:
  #'[output.ansi.enabled]': always
  datasource:
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://211.119.124.122:3306/xplatform?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xit5811807
    hikari:
      driver-class-name: ${spring.datasource.driver-class-name}
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      read-only: false

  devtools:
    livereload:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: debug
  file:
    path: D:/data/ens/logs

# Spring Security cors 설정 :: CorsConfiguration 설정 값
cors:
  allowed-origins: https://fonts.gstatic.com,http://localhost:3000,http://localhost,http://211.119.124.107,http://211.119.124.107:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Origin,X-Requested-With,Content-Type,Accept,Authorization,X-CSRF-TOKEN
  max-age: 3600
