#-----------------------------------------------------------------------
#   application 설정
#-----------------------------------------------------------------------
contract:
  kakao:
    pay:
      mydoc:
        host: https://docs-gw.kakaopay.com
        access-token: cc21fc83ae3d11ecb91e42193199ee3c
        contract-uuid: CON-cc375944ae3d11ecb91e42193199ee3c
        api:
          send: /v1/documents
          token: /v1/{documentBinderUuid}/tokens/{token}
          readcompleted: /v1/documents/{documentBinderUuid}
          status: /v1/documents/{documentBinderUuid}/status
          bulksend: /v1/documents/bulk
          bulksend-batch-unit: 100
          bulkstatus: /v1/documents/bulk/status
