#-----------------------------------------------------------------------
#
#   egovframework 설정
#
#-----------------------------------------------------------------------
#   1.  key = value 구조입니다.
#   2.  key값은 공백문자를 포함불가, value값은 공백문자를 가능
#   3.  key값으로 한글을 사용불가,   value값은 한글사용이 가능
#   4.  줄을 바꿀 필요가 있으면 '\'를 라인의 끝에 추가(만약  '\'문자를 사용해야 하는 경우는 '\\'를 사용)
#   5.  Windows에서의 디렉토리 표시 : '\\' or '/'  ('\' 사용하면 안됨)
#   6.  Unix에서의 디렉토리 표시 : '/'
#   7.  주석문 처리는  #사용
#   8.  value값 뒤에 스페이스가 존재하는 경우 서블릿에서 참조할때는 에러발생할 수 있으므로 trim()하거나 마지막 공백없이 properties 값을 설정할것
#-----------------------------------------------------------------------
Globals:
  # 운영서버 타입(WINDOWS, UNIX)
  OsType: UNIX

  # G4C 연결용 IP (localhost)
  LocalIp: 127.0.0.1

  # DB서버 타입(hsql,mysql,oracle,altibase,tibero) - datasource 및 sqlMap 파일 지정에 사용됨
  DbType: mysql

  #-----------------------------------------------------------------------
  # DB 접근 정보
  #-----------------------------------------------------------------------
  #hsql - local hssql 사용시에 적용 (내장 hsql은 정보 필요 없음)
  hsql:
    DriverClassName: net.sf.log4jdbc.DriverSpy
    Url: jdbc:log4jdbc:hsqldb:hsql://127.0.0.1/sampledb
    UserName: sa
    Password:

# mysql
  mysql:
    DriverClassName: net.sf.log4jdbc.DriverSpy
    Url: jdbc:log4jdbc:mariadb://211.119.124.122:3306/xplatform?useUnicode=true&characterEncoding=utf-8
    UserName: root
    Password: xit5811807

# MainPage Setting
  MainPage: /cmm/main/mainPage.do

  # 파일 확장자 화이트리스트(허용목록) : 파일 확장자를 (.)과 함께 연이어서 사용하며 (.)로 시작한다.
  fileUpload:
    Extensions: .gif.jpg.jpeg.png.xls.xlsx
    '[Images.Extensions]': .gif.jpg.jpeg.png

#server.servlet.context-path=/sht_boot_web
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path:
    session.timeout: 3600 #sec
    encoding:
      enabled: true
      charset: utf-8
      force: true

spring:
  profiles:
    active: '@springProfilesActive@'
    include:
    - app
    - jpa
    - ens

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#-----------------------------------------------------------------
# xit framework 설정
#-----------------------------------------------------------------
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: xit-hikari-pool
      auto-commit: false
      # 인프라의 적용된 connection time limit보다 작아야함
      max-lifetime: 1800000
      maximum-pool-size: 30
      minimum-idle: 5
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      data-source-properties:
        rewriteBatchedStatements: true

  main:
    allow-bean-definition-overriding: true
    #allow-circular-references: true

  devtools:
    livereload:
      enabled: false

springdoc:
  api-docs:
    enabled: false
    path: /api-docs
  swagger-ui:
    enabled: false # default true
    path: /swagger-ui.html
    csrf:
      enabled: false
  version: 'v1'   # API 문서 버전
  default-consumes-media-type: application/json # default consume media type
  default-produces-media-type: application/json # default produce media type
  model-and-view-allowed: true                  # ModelAndView 허용 - excel download시 필요

#-----------------------------------------------------------------
#  logback-spring.xml 로 설정시 스프링의 환경변수를 로그백 시스템 환경변수로 사용
#  logging.file.name / path => LOG_FILE,  LOG_PATH
#  logging.charset.console / file => CONSOLE_LOG_CHARSET, FILE_LOG_CHARSET
#  logging.pattern.console / file => CONSOLE_LOG_PATTERN, FILE_LOG_PATTERN
#-----------------------------------------------------------------
logging:
  charset:
    console: UTF-8
    file: UTF-8
  exception-conversion-word: '%wEx'
  level:
    root: error
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%18.18thread]){magenta} %clr([%-35.35logger{35}::%-25.25method{25}:%4line]){cyan} %clr(%m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}){faint}'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} [%18.18thread] [%-35.35logger{35}::%-25.25method{25}:%4line] %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
  file:
    path: /data/ens/logs
    name: ${app.name}

# Spring Security cors 설정 :: CorsConfiguration 설정 값
cors:
  # 헤더에 작성된 출처만 브라우저가 리소스를 접근할 수 있도록 허용함.
  # * 이면 모든 곳에 공개
  allowed-origins: http://localhost:8080,http:127.0.0.1:8080
  # 리소스 접근을 허용하는 HTTP 메서드를 지정
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  # 요청을 허용하는 해더
  allowed-headers: Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,X-Csrftoken,Authorization
  # 클라이언트에서 preflight 의 요청 결과를 저장할 기간을 지정
  # 60초 동안 preflight 요청을 캐시하는 설정으로, 첫 요청 이후 60초 동안은 OPTIONS 메소드를 사용하는 예비 요청을 보내지 않는다.
  max-Age: 60
  # 클라이언트 요청이 쿠키를 통해서 자격 증명을 해야 하는 경우에 true.
  # 자바스크립트 요청에서 credentials가 include일 때 요청에 대한 응답을 할 수 있는지를 나타낸다.
  allow-Credentials: true
  # 기본적으로 브라우저에게 노출이 되지 않지만, 브라우저 측에서 접근할 수 있게 허용해주는 헤더를 지정
  expose-Headers: Content-Length
